project:
  type: website
  output-dir: docs

website:
  title: "Julian Daduica's DSCI 521 Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: Contact_page.qmd
        text: Contact
      - href: grade_calculator.qmd
        text: Grade Calculator

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



